-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mis_task is
generic (
    C_M_AXI_L1_V_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_L1_V_ID_WIDTH : INTEGER := 1;
    C_M_AXI_L1_V_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_L1_V_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_L1_V_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_L1_V_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_L1_V_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_L1_V_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_L1_V_TARGET_ADDR : INTEGER := 0;
    C_M_AXI_L1_V_USER_VALUE : INTEGER := 0;
    C_M_AXI_L1_V_PROT_VALUE : INTEGER := 0;
    C_M_AXI_L1_V_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    task_in : IN STD_LOGIC_VECTOR (131 downto 0);
    task_out_V_TDATA : OUT STD_LOGIC_VECTOR (135 downto 0);
    task_out_V_TVALID : OUT STD_LOGIC;
    task_out_V_TREADY : IN STD_LOGIC;
    m_axi_l1_V_AWVALID : OUT STD_LOGIC;
    m_axi_l1_V_AWREADY : IN STD_LOGIC;
    m_axi_l1_V_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_L1_V_ADDR_WIDTH-1 downto 0);
    m_axi_l1_V_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_L1_V_ID_WIDTH-1 downto 0);
    m_axi_l1_V_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_l1_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_l1_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_l1_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_l1_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_l1_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_l1_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_l1_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_l1_V_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_L1_V_AWUSER_WIDTH-1 downto 0);
    m_axi_l1_V_WVALID : OUT STD_LOGIC;
    m_axi_l1_V_WREADY : IN STD_LOGIC;
    m_axi_l1_V_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_L1_V_DATA_WIDTH-1 downto 0);
    m_axi_l1_V_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_L1_V_DATA_WIDTH/8-1 downto 0);
    m_axi_l1_V_WLAST : OUT STD_LOGIC;
    m_axi_l1_V_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_L1_V_ID_WIDTH-1 downto 0);
    m_axi_l1_V_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_L1_V_WUSER_WIDTH-1 downto 0);
    m_axi_l1_V_ARVALID : OUT STD_LOGIC;
    m_axi_l1_V_ARREADY : IN STD_LOGIC;
    m_axi_l1_V_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_L1_V_ADDR_WIDTH-1 downto 0);
    m_axi_l1_V_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_L1_V_ID_WIDTH-1 downto 0);
    m_axi_l1_V_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_l1_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_l1_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_l1_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_l1_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_l1_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_l1_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_l1_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_l1_V_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_L1_V_ARUSER_WIDTH-1 downto 0);
    m_axi_l1_V_RVALID : IN STD_LOGIC;
    m_axi_l1_V_RREADY : OUT STD_LOGIC;
    m_axi_l1_V_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_L1_V_DATA_WIDTH-1 downto 0);
    m_axi_l1_V_RLAST : IN STD_LOGIC;
    m_axi_l1_V_RID : IN STD_LOGIC_VECTOR (C_M_AXI_L1_V_ID_WIDTH-1 downto 0);
    m_axi_l1_V_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_L1_V_RUSER_WIDTH-1 downto 0);
    m_axi_l1_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_l1_V_BVALID : IN STD_LOGIC;
    m_axi_l1_V_BREADY : OUT STD_LOGIC;
    m_axi_l1_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_l1_V_BID : IN STD_LOGIC_VECTOR (C_M_AXI_L1_V_ID_WIDTH-1 downto 0);
    m_axi_l1_V_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_L1_V_BUSER_WIDTH-1 downto 0);
    undo_log_entry_V_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    undo_log_entry_V_TVALID : OUT STD_LOGIC;
    undo_log_entry_V_TREADY : IN STD_LOGIC );
end;


architecture behav of mis_task is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "mis_task,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k160t-fbg484-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.500000,HLS_SYN_LAT=18,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=793,HLS_SYN_LUT=899,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (24 downto 0) := "0000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (24 downto 0) := "0000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (24 downto 0) := "0000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (24 downto 0) := "0000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (24 downto 0) := "0000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (24 downto 0) := "0000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (24 downto 0) := "0001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (24 downto 0) := "0010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (24 downto 0) := "0100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_3D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111101";
    constant ap_const_lv36_4 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000000100";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal initialized_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal base_flags_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal task_out_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal l1_V_blk_n_AR : STD_LOGIC;
    signal initialized_V_load_load_fu_131_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal l1_V_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal l1_V_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal l1_V_blk_n_W : STD_LOGIC;
    signal l1_V_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal icmp_ln879_reg_278 : STD_LOGIC_VECTOR (0 downto 0);
    signal undo_log_entry_V_TDATA_blk_n : STD_LOGIC;
    signal l1_V_AWVALID : STD_LOGIC;
    signal l1_V_AWREADY : STD_LOGIC;
    signal l1_V_WVALID : STD_LOGIC;
    signal l1_V_WREADY : STD_LOGIC;
    signal l1_V_ARVALID : STD_LOGIC;
    signal l1_V_ARREADY : STD_LOGIC;
    signal l1_V_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal l1_V_RVALID : STD_LOGIC;
    signal l1_V_RREADY : STD_LOGIC;
    signal l1_V_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal l1_V_RLAST : STD_LOGIC;
    signal l1_V_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal l1_V_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal l1_V_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal l1_V_BVALID : STD_LOGIC;
    signal l1_V_BREADY : STD_LOGIC;
    signal l1_V_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal l1_V_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal l1_V_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_io : BOOLEAN;
    signal vid_V_fu_154_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal vid_V_reg_256 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal base_flags_V_load_reg_261 : STD_LOGIC_VECTOR (31 downto 0);
    signal l1_V_addr_1_reg_266 : STD_LOGIC_VECTOR (31 downto 0);
    signal cur_flag_V_reg_273 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln879_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal add_ln1503_fu_208_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln1503_reg_282 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln176_fu_214_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln176_reg_287 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state20_io : BOOLEAN;
    signal sext_ln544_fu_181_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_task_out_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_undo_log_entry_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state25 : BOOLEAN;
    signal lhs_V_fu_167_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_fu_167_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal rhs_V_fu_171_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal ret_V_fu_175_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln1503_fu_196_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_2_fu_199_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_1_fu_227_p4 : STD_LOGIC_VECTOR (131 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_block_state21_io : BOOLEAN;
    signal task_out_V_TDATA_int : STD_LOGIC_VECTOR (135 downto 0);
    signal task_out_V_TVALID_int : STD_LOGIC;
    signal task_out_V_TREADY_int : STD_LOGIC;
    signal regslice_both_task_out_V_U_vld_out : STD_LOGIC;
    signal undo_log_entry_V_TDATA_int : STD_LOGIC_VECTOR (63 downto 0);
    signal undo_log_entry_V_TVALID_int : STD_LOGIC;
    signal undo_log_entry_V_TREADY_int : STD_LOGIC;
    signal regslice_both_undo_log_entry_V_U_vld_out : STD_LOGIC;

    component mis_task_l1_V_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_TARGET_ADDR : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    mis_task_l1_V_m_axi_U : component mis_task_l1_V_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 32,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_L1_V_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_L1_V_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_L1_V_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_L1_V_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_L1_V_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_L1_V_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_L1_V_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_L1_V_BUSER_WIDTH,
        C_TARGET_ADDR => C_M_AXI_L1_V_TARGET_ADDR,
        C_USER_VALUE => C_M_AXI_L1_V_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_L1_V_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_L1_V_CACHE_VALUE)
    port map (
        AWVALID => m_axi_l1_V_AWVALID,
        AWREADY => m_axi_l1_V_AWREADY,
        AWADDR => m_axi_l1_V_AWADDR,
        AWID => m_axi_l1_V_AWID,
        AWLEN => m_axi_l1_V_AWLEN,
        AWSIZE => m_axi_l1_V_AWSIZE,
        AWBURST => m_axi_l1_V_AWBURST,
        AWLOCK => m_axi_l1_V_AWLOCK,
        AWCACHE => m_axi_l1_V_AWCACHE,
        AWPROT => m_axi_l1_V_AWPROT,
        AWQOS => m_axi_l1_V_AWQOS,
        AWREGION => m_axi_l1_V_AWREGION,
        AWUSER => m_axi_l1_V_AWUSER,
        WVALID => m_axi_l1_V_WVALID,
        WREADY => m_axi_l1_V_WREADY,
        WDATA => m_axi_l1_V_WDATA,
        WSTRB => m_axi_l1_V_WSTRB,
        WLAST => m_axi_l1_V_WLAST,
        WID => m_axi_l1_V_WID,
        WUSER => m_axi_l1_V_WUSER,
        ARVALID => m_axi_l1_V_ARVALID,
        ARREADY => m_axi_l1_V_ARREADY,
        ARADDR => m_axi_l1_V_ARADDR,
        ARID => m_axi_l1_V_ARID,
        ARLEN => m_axi_l1_V_ARLEN,
        ARSIZE => m_axi_l1_V_ARSIZE,
        ARBURST => m_axi_l1_V_ARBURST,
        ARLOCK => m_axi_l1_V_ARLOCK,
        ARCACHE => m_axi_l1_V_ARCACHE,
        ARPROT => m_axi_l1_V_ARPROT,
        ARQOS => m_axi_l1_V_ARQOS,
        ARREGION => m_axi_l1_V_ARREGION,
        ARUSER => m_axi_l1_V_ARUSER,
        RVALID => m_axi_l1_V_RVALID,
        RREADY => m_axi_l1_V_RREADY,
        RDATA => m_axi_l1_V_RDATA,
        RLAST => m_axi_l1_V_RLAST,
        RID => m_axi_l1_V_RID,
        RUSER => m_axi_l1_V_RUSER,
        RRESP => m_axi_l1_V_RRESP,
        BVALID => m_axi_l1_V_BVALID,
        BREADY => m_axi_l1_V_BREADY,
        BRESP => m_axi_l1_V_BRESP,
        BID => m_axi_l1_V_BID,
        BUSER => m_axi_l1_V_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => l1_V_ARVALID,
        I_ARREADY => l1_V_ARREADY,
        I_ARADDR => l1_V_ARADDR,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => ap_const_lv32_1,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => l1_V_RVALID,
        I_RREADY => l1_V_RREADY,
        I_RDATA => l1_V_RDATA,
        I_RID => l1_V_RID,
        I_RUSER => l1_V_RUSER,
        I_RRESP => l1_V_RRESP,
        I_RLAST => l1_V_RLAST,
        I_AWVALID => l1_V_AWVALID,
        I_AWREADY => l1_V_AWREADY,
        I_AWADDR => l1_V_addr_1_reg_266,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_1,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => l1_V_WVALID,
        I_WREADY => l1_V_WREADY,
        I_WDATA => ap_const_lv32_1,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv4_F,
        I_BVALID => l1_V_BVALID,
        I_BREADY => l1_V_BREADY,
        I_BRESP => l1_V_BRESP,
        I_BID => l1_V_BID,
        I_BUSER => l1_V_BUSER);

    regslice_both_task_out_V_U : component regslice_both
    generic map (
        DataWidth => 136)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => task_out_V_TDATA_int,
        vld_in => task_out_V_TVALID_int,
        ack_in => task_out_V_TREADY_int,
        data_out => task_out_V_TDATA,
        vld_out => regslice_both_task_out_V_U_vld_out,
        ack_out => task_out_V_TREADY,
        apdone_blk => regslice_both_task_out_V_U_apdone_blk);

    regslice_both_undo_log_entry_V_U : component regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => undo_log_entry_V_TDATA_int,
        vld_in => undo_log_entry_V_TVALID_int,
        ack_in => undo_log_entry_V_TREADY_int,
        data_out => undo_log_entry_V_TDATA,
        vld_out => regslice_both_undo_log_entry_V_U_vld_out,
        ack_out => undo_log_entry_V_TREADY,
        apdone_blk => regslice_both_undo_log_entry_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state18) and (icmp_ln879_fu_191_p2 = ap_const_lv1_1))) then
                add_ln1503_reg_282 <= add_ln1503_fu_208_p2;
                trunc_ln176_reg_287 <= trunc_ln176_fu_214_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((l1_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                base_flags_V <= l1_V_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                base_flags_V_load_reg_261 <= base_flags_V;
                l1_V_addr_1_reg_266 <= sext_ln544_fu_181_p1(32 - 1 downto 0);
                vid_V_reg_256 <= task_in(63 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((l1_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                cur_flag_V_reg_273 <= l1_V_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                icmp_ln879_reg_278 <= icmp_ln879_fu_191_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (initialized_V = ap_const_lv1_0))) then
                initialized_V <= ap_const_lv1_1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, initialized_V, ap_CS_fsm_state20, ap_CS_fsm_state21, initialized_V_load_load_fu_131_p1, ap_CS_fsm_state8, ap_CS_fsm_state10, ap_CS_fsm_state17, ap_CS_fsm_state19, ap_CS_fsm_state25, icmp_ln879_reg_278, l1_V_AWREADY, l1_V_ARREADY, l1_V_RVALID, l1_V_BVALID, ap_block_state1_io, icmp_ln879_fu_191_p2, ap_CS_fsm_state18, ap_block_state20_io, regslice_both_task_out_V_U_apdone_blk, regslice_both_undo_log_entry_V_U_apdone_blk, ap_block_state21_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (initialized_V_load_load_fu_131_p1 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (initialized_V = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((l1_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((l1_V_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                if (((l1_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when ap_ST_fsm_state18 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state18) and (icmp_ln879_fu_191_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state25;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state19 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state19) and (l1_V_AWREADY = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state20 => 
                if (((ap_const_boolean_0 = ap_block_state20_io) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state21 => 
                if (((ap_const_boolean_0 = ap_block_state21_io) and (ap_const_logic_1 = ap_CS_fsm_state21))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_state21;
                end if;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                if ((not(((regslice_both_undo_log_entry_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_task_out_V_U_apdone_blk = ap_const_logic_1) or ((l1_V_BVALID = ap_const_logic_0) and (icmp_ln879_reg_278 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state25))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state25;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln1503_fu_208_p2 <= std_logic_vector(unsigned(trunc_ln1503_fu_196_p1) + unsigned(tmp_2_fu_199_p4));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state1_io_assign_proc : process(initialized_V, l1_V_ARREADY)
    begin
                ap_block_state1_io <= ((l1_V_ARREADY = ap_const_logic_0) and (initialized_V = ap_const_lv1_0));
    end process;


    ap_block_state20_io_assign_proc : process(l1_V_WREADY, task_out_V_TREADY_int, undo_log_entry_V_TREADY_int)
    begin
                ap_block_state20_io <= ((undo_log_entry_V_TREADY_int = ap_const_logic_0) or (task_out_V_TREADY_int = ap_const_logic_0) or (l1_V_WREADY = ap_const_logic_0));
    end process;


    ap_block_state21_io_assign_proc : process(task_out_V_TREADY_int, undo_log_entry_V_TREADY_int)
    begin
                ap_block_state21_io <= ((undo_log_entry_V_TREADY_int = ap_const_logic_0) or (task_out_V_TREADY_int = ap_const_logic_0));
    end process;


    ap_block_state25_assign_proc : process(icmp_ln879_reg_278, l1_V_BVALID, regslice_both_task_out_V_U_apdone_blk, regslice_both_undo_log_entry_V_U_apdone_blk)
    begin
                ap_block_state25 <= ((regslice_both_undo_log_entry_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_task_out_V_U_apdone_blk = ap_const_logic_1) or ((l1_V_BVALID = ap_const_logic_0) and (icmp_ln879_reg_278 = ap_const_lv1_1)));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state25, icmp_ln879_reg_278, l1_V_BVALID, regslice_both_task_out_V_U_apdone_blk, regslice_both_undo_log_entry_V_U_apdone_blk)
    begin
        if ((not(((regslice_both_undo_log_entry_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_task_out_V_U_apdone_blk = ap_const_logic_1) or ((l1_V_BVALID = ap_const_logic_0) and (icmp_ln879_reg_278 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state25, icmp_ln879_reg_278, l1_V_BVALID, regslice_both_task_out_V_U_apdone_blk, regslice_both_undo_log_entry_V_U_apdone_blk)
    begin
        if ((not(((regslice_both_undo_log_entry_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_task_out_V_U_apdone_blk = ap_const_logic_1) or ((l1_V_BVALID = ap_const_logic_0) and (icmp_ln879_reg_278 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    icmp_ln879_fu_191_p2 <= "1" when (cur_flag_V_reg_273 = ap_const_lv32_0) else "0";
    initialized_V_load_load_fu_131_p1 <= initialized_V;

    l1_V_ARADDR_assign_proc : process(ap_start, ap_CS_fsm_state1, initialized_V, ap_CS_fsm_state10, l1_V_ARREADY, ap_block_state1_io, l1_V_addr_1_reg_266)
    begin
        if (((l1_V_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            l1_V_ARADDR <= l1_V_addr_1_reg_266;
        elsif ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (initialized_V = ap_const_lv1_0))) then 
            l1_V_ARADDR <= ap_const_lv64_3(32 - 1 downto 0);
        else 
            l1_V_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    l1_V_ARVALID_assign_proc : process(ap_start, ap_CS_fsm_state1, initialized_V, ap_CS_fsm_state10, l1_V_ARREADY, ap_block_state1_io)
    begin
        if (((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (initialized_V = ap_const_lv1_0)) or ((l1_V_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            l1_V_ARVALID <= ap_const_logic_1;
        else 
            l1_V_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    l1_V_AWVALID_assign_proc : process(ap_CS_fsm_state19, l1_V_AWREADY)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state19) and (l1_V_AWREADY = ap_const_logic_1))) then 
            l1_V_AWVALID <= ap_const_logic_1;
        else 
            l1_V_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    l1_V_BREADY_assign_proc : process(ap_CS_fsm_state25, icmp_ln879_reg_278, l1_V_BVALID, regslice_both_task_out_V_U_apdone_blk, regslice_both_undo_log_entry_V_U_apdone_blk)
    begin
        if ((not(((regslice_both_undo_log_entry_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_task_out_V_U_apdone_blk = ap_const_logic_1) or ((l1_V_BVALID = ap_const_logic_0) and (icmp_ln879_reg_278 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state25) and (icmp_ln879_reg_278 = ap_const_lv1_1))) then 
            l1_V_BREADY <= ap_const_logic_1;
        else 
            l1_V_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    l1_V_RREADY_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state17, l1_V_RVALID)
    begin
        if ((((l1_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state17)) or ((l1_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8)))) then 
            l1_V_RREADY <= ap_const_logic_1;
        else 
            l1_V_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    l1_V_WVALID_assign_proc : process(ap_CS_fsm_state20, ap_block_state20_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state20_io) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            l1_V_WVALID <= ap_const_logic_1;
        else 
            l1_V_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    l1_V_blk_n_AR_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_l1_V_ARREADY, initialized_V, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (initialized_V = ap_const_lv1_0)))) then 
            l1_V_blk_n_AR <= m_axi_l1_V_ARREADY;
        else 
            l1_V_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    l1_V_blk_n_AW_assign_proc : process(m_axi_l1_V_AWREADY, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            l1_V_blk_n_AW <= m_axi_l1_V_AWREADY;
        else 
            l1_V_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    l1_V_blk_n_B_assign_proc : process(m_axi_l1_V_BVALID, ap_CS_fsm_state25, icmp_ln879_reg_278)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and (icmp_ln879_reg_278 = ap_const_lv1_1))) then 
            l1_V_blk_n_B <= m_axi_l1_V_BVALID;
        else 
            l1_V_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    l1_V_blk_n_R_assign_proc : process(m_axi_l1_V_RVALID, ap_CS_fsm_state8, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            l1_V_blk_n_R <= m_axi_l1_V_RVALID;
        else 
            l1_V_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    l1_V_blk_n_W_assign_proc : process(m_axi_l1_V_WREADY, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            l1_V_blk_n_W <= m_axi_l1_V_WREADY;
        else 
            l1_V_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    lhs_V_fu_167_p0 <= base_flags_V;
        lhs_V_fu_167_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lhs_V_fu_167_p0),34));

    ret_V_fu_175_p2 <= std_logic_vector(signed(lhs_V_fu_167_p1) + signed(rhs_V_fu_171_p1));
    rhs_V_fu_171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vid_V_fu_154_p4),34));
        sext_ln544_fu_181_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_fu_175_p2),64));


    task_out_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state21, task_out_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            task_out_V_TDATA_blk_n <= task_out_V_TREADY_int;
        else 
            task_out_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        task_out_V_TDATA_int <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_227_p4),136));

    task_out_V_TVALID <= regslice_both_task_out_V_U_vld_out;

    task_out_V_TVALID_int_assign_proc : process(ap_CS_fsm_state20, ap_block_state20_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state20_io) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            task_out_V_TVALID_int <= ap_const_logic_1;
        else 
            task_out_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_227_p4 <= ((vid_V_reg_256 & ap_const_lv36_4) & trunc_ln176_reg_287);
    tmp_2_fu_199_p4 <= task_in(61 downto 32);
    trunc_ln1503_fu_196_p1 <= base_flags_V_load_reg_261(30 - 1 downto 0);
    trunc_ln176_fu_214_p1 <= task_in(64 - 1 downto 0);

    undo_log_entry_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state21, undo_log_entry_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            undo_log_entry_V_TDATA_blk_n <= undo_log_entry_V_TREADY_int;
        else 
            undo_log_entry_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    undo_log_entry_V_TDATA_int <= ((ap_const_lv32_0 & add_ln1503_reg_282) & ap_const_lv2_0);
    undo_log_entry_V_TVALID <= regslice_both_undo_log_entry_V_U_vld_out;

    undo_log_entry_V_TVALID_int_assign_proc : process(ap_CS_fsm_state20, ap_block_state20_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state20_io) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            undo_log_entry_V_TVALID_int <= ap_const_logic_1;
        else 
            undo_log_entry_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    vid_V_fu_154_p4 <= task_in(63 downto 32);
end behav;
