// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mis_hls,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k160t-fbg484-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.500000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=4,HLS_SYN_FF=1377,HLS_SYN_LUT=1253,HLS_VERSION=2019_2}" *)

module mis_hls (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        task_in,
        task_out_V_TDATA,
        task_out_V_TVALID,
        task_out_V_TREADY,
        m_axi_l1_V_AWVALID,
        m_axi_l1_V_AWREADY,
        m_axi_l1_V_AWADDR,
        m_axi_l1_V_AWID,
        m_axi_l1_V_AWLEN,
        m_axi_l1_V_AWSIZE,
        m_axi_l1_V_AWBURST,
        m_axi_l1_V_AWLOCK,
        m_axi_l1_V_AWCACHE,
        m_axi_l1_V_AWPROT,
        m_axi_l1_V_AWQOS,
        m_axi_l1_V_AWREGION,
        m_axi_l1_V_AWUSER,
        m_axi_l1_V_WVALID,
        m_axi_l1_V_WREADY,
        m_axi_l1_V_WDATA,
        m_axi_l1_V_WSTRB,
        m_axi_l1_V_WLAST,
        m_axi_l1_V_WID,
        m_axi_l1_V_WUSER,
        m_axi_l1_V_ARVALID,
        m_axi_l1_V_ARREADY,
        m_axi_l1_V_ARADDR,
        m_axi_l1_V_ARID,
        m_axi_l1_V_ARLEN,
        m_axi_l1_V_ARSIZE,
        m_axi_l1_V_ARBURST,
        m_axi_l1_V_ARLOCK,
        m_axi_l1_V_ARCACHE,
        m_axi_l1_V_ARPROT,
        m_axi_l1_V_ARQOS,
        m_axi_l1_V_ARREGION,
        m_axi_l1_V_ARUSER,
        m_axi_l1_V_RVALID,
        m_axi_l1_V_RREADY,
        m_axi_l1_V_RDATA,
        m_axi_l1_V_RLAST,
        m_axi_l1_V_RID,
        m_axi_l1_V_RUSER,
        m_axi_l1_V_RRESP,
        m_axi_l1_V_BVALID,
        m_axi_l1_V_BREADY,
        m_axi_l1_V_BRESP,
        m_axi_l1_V_BID,
        m_axi_l1_V_BUSER,
        undo_log_entry_V_TDATA,
        undo_log_entry_V_TVALID,
        undo_log_entry_V_TREADY
);

parameter    ap_ST_fsm_state1 = 34'd1;
parameter    ap_ST_fsm_state2 = 34'd2;
parameter    ap_ST_fsm_state3 = 34'd4;
parameter    ap_ST_fsm_state4 = 34'd8;
parameter    ap_ST_fsm_state5 = 34'd16;
parameter    ap_ST_fsm_state6 = 34'd32;
parameter    ap_ST_fsm_state7 = 34'd64;
parameter    ap_ST_fsm_state8 = 34'd128;
parameter    ap_ST_fsm_state9 = 34'd256;
parameter    ap_ST_fsm_state10 = 34'd512;
parameter    ap_ST_fsm_state11 = 34'd1024;
parameter    ap_ST_fsm_state12 = 34'd2048;
parameter    ap_ST_fsm_state13 = 34'd4096;
parameter    ap_ST_fsm_state14 = 34'd8192;
parameter    ap_ST_fsm_state15 = 34'd16384;
parameter    ap_ST_fsm_state16 = 34'd32768;
parameter    ap_ST_fsm_state17 = 34'd65536;
parameter    ap_ST_fsm_state18 = 34'd131072;
parameter    ap_ST_fsm_state19 = 34'd262144;
parameter    ap_ST_fsm_state20 = 34'd524288;
parameter    ap_ST_fsm_state21 = 34'd1048576;
parameter    ap_ST_fsm_state22 = 34'd2097152;
parameter    ap_ST_fsm_state23 = 34'd4194304;
parameter    ap_ST_fsm_state24 = 34'd8388608;
parameter    ap_ST_fsm_state25 = 34'd16777216;
parameter    ap_ST_fsm_state26 = 34'd33554432;
parameter    ap_ST_fsm_state27 = 34'd67108864;
parameter    ap_ST_fsm_state28 = 34'd134217728;
parameter    ap_ST_fsm_state29 = 34'd268435456;
parameter    ap_ST_fsm_state30 = 34'd536870912;
parameter    ap_ST_fsm_state31 = 34'd1073741824;
parameter    ap_ST_fsm_state32 = 34'd2147483648;
parameter    ap_ST_fsm_state33 = 34'd4294967296;
parameter    ap_ST_fsm_state34 = 34'd8589934592;
parameter    C_M_AXI_L1_V_ID_WIDTH = 1;
parameter    C_M_AXI_L1_V_ADDR_WIDTH = 32;
parameter    C_M_AXI_L1_V_DATA_WIDTH = 32;
parameter    C_M_AXI_L1_V_AWUSER_WIDTH = 1;
parameter    C_M_AXI_L1_V_ARUSER_WIDTH = 1;
parameter    C_M_AXI_L1_V_WUSER_WIDTH = 1;
parameter    C_M_AXI_L1_V_RUSER_WIDTH = 1;
parameter    C_M_AXI_L1_V_BUSER_WIDTH = 1;
parameter    C_M_AXI_L1_V_TARGET_ADDR = 0;
parameter    C_M_AXI_L1_V_USER_VALUE = 0;
parameter    C_M_AXI_L1_V_PROT_VALUE = 0;
parameter    C_M_AXI_L1_V_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_L1_V_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [131:0] task_in;
output  [135:0] task_out_V_TDATA;
output   task_out_V_TVALID;
input   task_out_V_TREADY;
output   m_axi_l1_V_AWVALID;
input   m_axi_l1_V_AWREADY;
output  [C_M_AXI_L1_V_ADDR_WIDTH - 1:0] m_axi_l1_V_AWADDR;
output  [C_M_AXI_L1_V_ID_WIDTH - 1:0] m_axi_l1_V_AWID;
output  [7:0] m_axi_l1_V_AWLEN;
output  [2:0] m_axi_l1_V_AWSIZE;
output  [1:0] m_axi_l1_V_AWBURST;
output  [1:0] m_axi_l1_V_AWLOCK;
output  [3:0] m_axi_l1_V_AWCACHE;
output  [2:0] m_axi_l1_V_AWPROT;
output  [3:0] m_axi_l1_V_AWQOS;
output  [3:0] m_axi_l1_V_AWREGION;
output  [C_M_AXI_L1_V_AWUSER_WIDTH - 1:0] m_axi_l1_V_AWUSER;
output   m_axi_l1_V_WVALID;
input   m_axi_l1_V_WREADY;
output  [C_M_AXI_L1_V_DATA_WIDTH - 1:0] m_axi_l1_V_WDATA;
output  [C_M_AXI_L1_V_WSTRB_WIDTH - 1:0] m_axi_l1_V_WSTRB;
output   m_axi_l1_V_WLAST;
output  [C_M_AXI_L1_V_ID_WIDTH - 1:0] m_axi_l1_V_WID;
output  [C_M_AXI_L1_V_WUSER_WIDTH - 1:0] m_axi_l1_V_WUSER;
output   m_axi_l1_V_ARVALID;
input   m_axi_l1_V_ARREADY;
output  [C_M_AXI_L1_V_ADDR_WIDTH - 1:0] m_axi_l1_V_ARADDR;
output  [C_M_AXI_L1_V_ID_WIDTH - 1:0] m_axi_l1_V_ARID;
output  [7:0] m_axi_l1_V_ARLEN;
output  [2:0] m_axi_l1_V_ARSIZE;
output  [1:0] m_axi_l1_V_ARBURST;
output  [1:0] m_axi_l1_V_ARLOCK;
output  [3:0] m_axi_l1_V_ARCACHE;
output  [2:0] m_axi_l1_V_ARPROT;
output  [3:0] m_axi_l1_V_ARQOS;
output  [3:0] m_axi_l1_V_ARREGION;
output  [C_M_AXI_L1_V_ARUSER_WIDTH - 1:0] m_axi_l1_V_ARUSER;
input   m_axi_l1_V_RVALID;
output   m_axi_l1_V_RREADY;
input  [C_M_AXI_L1_V_DATA_WIDTH - 1:0] m_axi_l1_V_RDATA;
input   m_axi_l1_V_RLAST;
input  [C_M_AXI_L1_V_ID_WIDTH - 1:0] m_axi_l1_V_RID;
input  [C_M_AXI_L1_V_RUSER_WIDTH - 1:0] m_axi_l1_V_RUSER;
input  [1:0] m_axi_l1_V_RRESP;
input   m_axi_l1_V_BVALID;
output   m_axi_l1_V_BREADY;
input  [1:0] m_axi_l1_V_BRESP;
input  [C_M_AXI_L1_V_ID_WIDTH - 1:0] m_axi_l1_V_BID;
input  [C_M_AXI_L1_V_BUSER_WIDTH - 1:0] m_axi_l1_V_BUSER;
input  [63:0] undo_log_entry_V_TDATA;
input   undo_log_entry_V_TVALID;
output   undo_log_entry_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg undo_log_entry_V_TREADY;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [33:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] initialized_V;
reg   [31:0] base_neighbor_V;
reg   [31:0] base_degree_V;
reg   [31:0] total_v_V;
reg    task_out_V_TDATA_blk_n;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;
reg   [0:0] icmp_ln887_1_reg_559;
wire    ap_CS_fsm_state19;
wire   [0:0] icmp_ln887_fu_346_p2;
wire   [0:0] icmp_ln887_2_fu_372_p2;
wire    ap_CS_fsm_state34;
reg   [0:0] icmp_ln879_reg_500;
reg   [0:0] icmp_ln887_2_reg_573;
reg    l1_V_blk_n_AR;
wire   [0:0] initialized_V_load_load_fu_185_p1;
reg    l1_V_blk_n_R;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state10;
reg   [0:0] initialized_V_load_reg_478;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state25;
wire    l1_V_AWREADY;
wire    l1_V_WREADY;
reg    l1_V_ARVALID;
wire    l1_V_ARREADY;
reg   [31:0] l1_V_ARADDR;
wire    l1_V_RVALID;
reg    l1_V_RREADY;
wire   [31:0] l1_V_RDATA;
wire    l1_V_RLAST;
wire   [0:0] l1_V_RID;
wire   [0:0] l1_V_RUSER;
wire   [1:0] l1_V_RRESP;
wire    l1_V_BVALID;
wire   [1:0] l1_V_BRESP;
wire   [0:0] l1_V_BID;
wire   [0:0] l1_V_BUSER;
reg    ap_block_state1_io;
wire   [0:0] icmp_ln879_fu_243_p2;
reg    ap_block_state10;
reg   [31:0] l1_V_addr_3_reg_510;
wire  signed [31:0] start_n_V_fu_286_p4;
reg  signed [31:0] start_n_V_reg_516;
wire    ap_CS_fsm_state17;
wire   [32:0] ret_V_1_fu_299_p2;
reg   [32:0] ret_V_1_reg_524;
wire   [31:0] i_V_fu_305_p4;
reg   [31:0] i_V_reg_529;
reg   [31:0] n_V_reg_534;
wire   [33:0] zext_ln177_1_fu_314_p1;
reg   [33:0] zext_ln177_1_reg_540;
wire   [31:0] ngh_cnt_V_fu_331_p3;
reg   [31:0] ngh_cnt_V_reg_545;
wire   [63:0] lhs_V_2_fu_338_p1;
reg   [63:0] lhs_V_2_reg_551;
wire   [0:0] icmp_ln887_1_fu_351_p2;
reg    ap_predicate_op124_write_state19;
reg    ap_block_state19_io;
wire   [31:0] child_ts_V_fu_369_p1;
reg   [31:0] child_ts_V_reg_568;
wire  signed [135:0] sext_ln177_1_fu_389_p1;
wire   [63:0] grp_fu_364_p2;
reg   [63:0] ret_V_2_reg_582;
wire    ap_CS_fsm_state23;
wire   [32:0] add_ln544_fu_406_p2;
reg   [32:0] add_ln544_reg_587;
reg   [31:0] l1_V_addr_4_reg_592;
wire    ap_CS_fsm_state24;
wire  signed [135:0] sext_ln177_fu_452_p1;
wire   [31:0] ngh_cnt_V_1_fu_462_p2;
reg    ap_block_state33_io;
reg  signed [31:0] t_V_reg_175;
wire  signed [63:0] sext_ln544_fu_276_p1;
wire   [63:0] add_ln544_1_fu_415_p2;
reg   [63:0] p_Val2_s_fu_98;
wire   [63:0] p_Result_s_fu_429_p5;
wire   [3:0] task_in_ttype_V_load_fu_234_p4;
wire   [31:0] vid_V_fu_249_p4;
wire  signed [33:0] lhs_V_fu_262_p1;
wire   [33:0] rhs_V_fu_266_p1;
wire   [33:0] ret_V_fu_270_p2;
wire   [32:0] zext_ln177_fu_295_p1;
wire  signed [33:0] empty_fu_317_p1;
wire   [0:0] empty_8_fu_320_p2;
wire   [31:0] empty_9_fu_326_p2;
wire  signed [33:0] sext_ln887_fu_342_p1;
wire   [31:0] grp_fu_364_p0;
wire   [31:0] grp_fu_364_p1;
wire   [63:0] trunc_ln176_fu_376_p1;
wire   [131:0] tmp_1_fu_379_p5;
wire  signed [32:0] sext_ln544_1_fu_398_p1;
wire  signed [32:0] sext_ln544_2_fu_402_p1;
wire  signed [63:0] sext_ln544_3_fu_412_p1;
wire   [131:0] tmp_fu_441_p5;
reg    grp_fu_364_ce;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    regslice_both_task_out_V_U_apdone_blk;
reg    ap_predicate_op154_write_state34;
reg    ap_block_state34_io;
reg   [33:0] ap_NS_fsm;
reg   [135:0] task_out_V_TDATA_int;
reg    task_out_V_TVALID_int;
wire    task_out_V_TREADY_int;
wire    regslice_both_task_out_V_U_vld_out;
wire    regslice_both_undo_log_entry_V_U_apdone_blk;
wire   [63:0] undo_log_entry_V_TDATA_int;
wire    undo_log_entry_V_TVALID_int;
wire    regslice_both_undo_log_entry_V_U_ack_in;
wire   [63:0] grp_fu_364_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 34'd1;
#0 initialized_V = 1'd0;
#0 base_neighbor_V = 32'd0;
#0 base_degree_V = 32'd0;
#0 total_v_V = 32'd0;
end

mis_hls_l1_V_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_L1_V_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_L1_V_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_L1_V_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_L1_V_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_L1_V_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_L1_V_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_L1_V_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_L1_V_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_L1_V_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_L1_V_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_L1_V_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_L1_V_CACHE_VALUE ))
mis_hls_l1_V_m_axi_U(
    .AWVALID(m_axi_l1_V_AWVALID),
    .AWREADY(m_axi_l1_V_AWREADY),
    .AWADDR(m_axi_l1_V_AWADDR),
    .AWID(m_axi_l1_V_AWID),
    .AWLEN(m_axi_l1_V_AWLEN),
    .AWSIZE(m_axi_l1_V_AWSIZE),
    .AWBURST(m_axi_l1_V_AWBURST),
    .AWLOCK(m_axi_l1_V_AWLOCK),
    .AWCACHE(m_axi_l1_V_AWCACHE),
    .AWPROT(m_axi_l1_V_AWPROT),
    .AWQOS(m_axi_l1_V_AWQOS),
    .AWREGION(m_axi_l1_V_AWREGION),
    .AWUSER(m_axi_l1_V_AWUSER),
    .WVALID(m_axi_l1_V_WVALID),
    .WREADY(m_axi_l1_V_WREADY),
    .WDATA(m_axi_l1_V_WDATA),
    .WSTRB(m_axi_l1_V_WSTRB),
    .WLAST(m_axi_l1_V_WLAST),
    .WID(m_axi_l1_V_WID),
    .WUSER(m_axi_l1_V_WUSER),
    .ARVALID(m_axi_l1_V_ARVALID),
    .ARREADY(m_axi_l1_V_ARREADY),
    .ARADDR(m_axi_l1_V_ARADDR),
    .ARID(m_axi_l1_V_ARID),
    .ARLEN(m_axi_l1_V_ARLEN),
    .ARSIZE(m_axi_l1_V_ARSIZE),
    .ARBURST(m_axi_l1_V_ARBURST),
    .ARLOCK(m_axi_l1_V_ARLOCK),
    .ARCACHE(m_axi_l1_V_ARCACHE),
    .ARPROT(m_axi_l1_V_ARPROT),
    .ARQOS(m_axi_l1_V_ARQOS),
    .ARREGION(m_axi_l1_V_ARREGION),
    .ARUSER(m_axi_l1_V_ARUSER),
    .RVALID(m_axi_l1_V_RVALID),
    .RREADY(m_axi_l1_V_RREADY),
    .RDATA(m_axi_l1_V_RDATA),
    .RLAST(m_axi_l1_V_RLAST),
    .RID(m_axi_l1_V_RID),
    .RUSER(m_axi_l1_V_RUSER),
    .RRESP(m_axi_l1_V_RRESP),
    .BVALID(m_axi_l1_V_BVALID),
    .BREADY(m_axi_l1_V_BREADY),
    .BRESP(m_axi_l1_V_BRESP),
    .BID(m_axi_l1_V_BID),
    .BUSER(m_axi_l1_V_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(l1_V_ARVALID),
    .I_ARREADY(l1_V_ARREADY),
    .I_ARADDR(l1_V_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(l1_V_RVALID),
    .I_RREADY(l1_V_RREADY),
    .I_RDATA(l1_V_RDATA),
    .I_RID(l1_V_RID),
    .I_RUSER(l1_V_RUSER),
    .I_RRESP(l1_V_RRESP),
    .I_RLAST(l1_V_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(l1_V_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(l1_V_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(l1_V_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(l1_V_BRESP),
    .I_BID(l1_V_BID),
    .I_BUSER(l1_V_BUSER)
);

mis_hls_mul_32ns_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mis_hls_mul_32ns_bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_364_p0),
    .din1(grp_fu_364_p1),
    .ce(grp_fu_364_ce),
    .dout(grp_fu_364_p2)
);

regslice_both #(
    .DataWidth( 136 ))
regslice_both_task_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(task_out_V_TDATA_int),
    .vld_in(task_out_V_TVALID_int),
    .ack_in(task_out_V_TREADY_int),
    .data_out(task_out_V_TDATA),
    .vld_out(regslice_both_task_out_V_U_vld_out),
    .ack_out(task_out_V_TREADY),
    .apdone_blk(regslice_both_task_out_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_undo_log_entry_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(undo_log_entry_V_TDATA),
    .vld_in(undo_log_entry_V_TVALID),
    .ack_in(regslice_both_undo_log_entry_V_U_ack_in),
    .data_out(undo_log_entry_V_TDATA_int),
    .vld_out(undo_log_entry_V_TVALID_int),
    .ack_out(1'b0),
    .apdone_blk(regslice_both_undo_log_entry_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state33_io) & (1'b1 == ap_CS_fsm_state33))) begin
        t_V_reg_175 <= ngh_cnt_V_1_fu_462_p2;
    end else if (((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        t_V_reg_175 <= start_n_V_reg_516;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        add_ln544_reg_587 <= add_ln544_fu_406_p2;
        ret_V_2_reg_582 <= grp_fu_364_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        base_degree_V <= l1_V_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        base_neighbor_V <= l1_V_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state19_io) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln887_1_fu_351_p2 == 1'd1) & (icmp_ln887_fu_346_p2 == 1'd1))) begin
        child_ts_V_reg_568 <= child_ts_V_fu_369_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        i_V_reg_529 <= {{task_in[131:100]}};
        lhs_V_2_reg_551[31 : 0] <= lhs_V_2_fu_338_p1[31 : 0];
        n_V_reg_534 <= l1_V_RDATA;
        ngh_cnt_V_reg_545 <= ngh_cnt_V_fu_331_p3;
        zext_ln177_1_reg_540[32 : 0] <= zext_ln177_1_fu_314_p1[32 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~((l1_V_RVALID == 1'b0) & (initialized_V_load_reg_478 == 1'd0)) & (1'b1 == ap_CS_fsm_state10))) begin
        icmp_ln879_reg_500 <= icmp_ln879_fu_243_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state19_io) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln887_fu_346_p2 == 1'd1))) begin
        icmp_ln887_1_reg_559 <= icmp_ln887_1_fu_351_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state19_io) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln887_fu_346_p2 == 1'd0))) begin
        icmp_ln887_2_reg_573 <= icmp_ln887_2_fu_372_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_io) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (initialized_V == 1'd0))) begin
        initialized_V <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_io) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        initialized_V_load_reg_478 <= initialized_V;
    end
end

always @ (posedge ap_clk) begin
    if ((~((l1_V_RVALID == 1'b0) & (initialized_V_load_reg_478 == 1'd0)) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln879_fu_243_p2 == 1'd1))) begin
        l1_V_addr_3_reg_510 <= sext_ln544_fu_276_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        l1_V_addr_4_reg_592 <= add_ln544_1_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((task_out_V_TREADY_int == 1'b0) | (l1_V_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state32))) begin
        p_Val2_s_fu_98 <= p_Result_s_fu_429_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ret_V_1_reg_524 <= ret_V_1_fu_299_p2;
        start_n_V_reg_516 <= {{task_in[99:68]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((l1_V_RVALID == 1'b0) & (initialized_V_load_reg_478 == 1'd0)) & (1'b1 == ap_CS_fsm_state10) & (initialized_V_load_reg_478 == 1'd0))) begin
        total_v_V <= l1_V_RDATA;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state34_io) | (regslice_both_task_out_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state34))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state34_io) | (regslice_both_task_out_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state34))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state23) | ((1'b0 == ap_block_state19_io) & (1'b1 == ap_CS_fsm_state19)))) begin
        grp_fu_364_ce = 1'b1;
    end else begin
        grp_fu_364_ce = 1'b0;
    end
end

always @ (*) begin
    if (((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        l1_V_ARADDR = l1_V_addr_4_reg_592;
    end else if (((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        l1_V_ARADDR = l1_V_addr_3_reg_510;
    end else if (((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        l1_V_ARADDR = 64'd1;
    end else if (((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        l1_V_ARADDR = 64'd5;
    end else if ((~((1'b1 == ap_block_state1_io) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (initialized_V == 1'd0))) begin
        l1_V_ARADDR = 64'd4;
    end else begin
        l1_V_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state1_io) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (initialized_V == 1'd0)) | ((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25)) | ((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        l1_V_ARVALID = 1'b1;
    end else begin
        l1_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | (~((l1_V_RVALID == 1'b0) & (initialized_V_load_reg_478 == 1'd0)) & (1'b1 == ap_CS_fsm_state10) & (initialized_V_load_reg_478 == 1'd0)) | ((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | (~((task_out_V_TREADY_int == 1'b0) | (l1_V_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state32)))) begin
        l1_V_RREADY = 1'b1;
    end else begin
        l1_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (initialized_V == 1'd0)))) begin
        l1_V_blk_n_AR = m_axi_l1_V_ARREADY;
    end else begin
        l1_V_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state32) | ((1'b1 == ap_CS_fsm_state10) & (initialized_V_load_reg_478 == 1'd0)))) begin
        l1_V_blk_n_R = m_axi_l1_V_RVALID;
    end else begin
        l1_V_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | ((1'b1 == ap_CS_fsm_state34) & (icmp_ln887_2_reg_573 == 1'd1) & (icmp_ln879_reg_500 == 1'd1)) | ((1'b1 == ap_CS_fsm_state19) & (icmp_ln887_2_fu_372_p2 == 1'd1) & (icmp_ln887_fu_346_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state33) & (icmp_ln887_1_reg_559 == 1'd1)))) begin
        task_out_V_TDATA_blk_n = task_out_V_TREADY_int;
    end else begin
        task_out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
        task_out_V_TDATA_int = sext_ln177_fu_452_p1;
    end else if (((ap_predicate_op124_write_state19 == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        task_out_V_TDATA_int = sext_ln177_1_fu_389_p1;
    end else begin
        task_out_V_TDATA_int = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op124_write_state19 == 1'b1) & (1'b0 == ap_block_state19_io) & (1'b1 == ap_CS_fsm_state19)) | (~((task_out_V_TREADY_int == 1'b0) | (l1_V_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state32)))) begin
        task_out_V_TVALID_int = 1'b1;
    end else begin
        task_out_V_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_undo_log_entry_V_U_ack_in == 1'b1) & (undo_log_entry_V_TVALID == 1'b1))) begin
        undo_log_entry_V_TREADY = 1'b1;
    end else begin
        undo_log_entry_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b1 == ap_block_state1_io) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (initialized_V_load_load_fu_185_p1 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if ((~((1'b1 == ap_block_state1_io) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (initialized_V == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if ((~((l1_V_RVALID == 1'b0) & (initialized_V_load_reg_478 == 1'd0)) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln879_fu_243_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else if ((~((l1_V_RVALID == 1'b0) & (initialized_V_load_reg_478 == 1'd0)) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln879_fu_243_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((l1_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((1'b0 == ap_block_state19_io) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln887_fu_346_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else if (((1'b0 == ap_block_state19_io) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln887_fu_346_p2 == 1'd1) & (icmp_ln887_1_fu_351_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else if (((1'b0 == ap_block_state19_io) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln887_1_fu_351_p2 == 1'd1) & (icmp_ln887_fu_346_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((l1_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if ((~((task_out_V_TREADY_int == 1'b0) | (l1_V_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            if (((1'b0 == ap_block_state33_io) & (1'b1 == ap_CS_fsm_state33))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state34 : begin
            if ((~((1'b1 == ap_block_state34_io) | (regslice_both_task_out_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln544_1_fu_415_p2 = ($signed(ret_V_2_reg_582) + $signed(sext_ln544_3_fu_412_p1));

assign add_ln544_fu_406_p2 = ($signed(sext_ln544_1_fu_398_p1) + $signed(sext_ln544_2_fu_402_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10 = ((l1_V_RVALID == 1'b0) & (initialized_V_load_reg_478 == 1'd0));
end

always @ (*) begin
    ap_block_state19_io = ((ap_predicate_op124_write_state19 == 1'b1) & (task_out_V_TREADY_int == 1'b0));
end

always @ (*) begin
    ap_block_state1_io = ((l1_V_ARREADY == 1'b0) & (initialized_V == 1'd0));
end

always @ (*) begin
    ap_block_state33_io = ((task_out_V_TREADY_int == 1'b0) & (icmp_ln887_1_reg_559 == 1'd1));
end

always @ (*) begin
    ap_block_state34_io = ((ap_predicate_op154_write_state34 == 1'b1) & (task_out_V_TREADY_int == 1'b0));
end

always @ (*) begin
    ap_predicate_op124_write_state19 = ((icmp_ln887_2_fu_372_p2 == 1'd1) & (icmp_ln887_fu_346_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op154_write_state34 = ((icmp_ln887_2_reg_573 == 1'd1) & (icmp_ln879_reg_500 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign child_ts_V_fu_369_p1 = task_in[31:0];

assign empty_8_fu_320_p2 = (($signed(zext_ln177_1_fu_314_p1) > $signed(empty_fu_317_p1)) ? 1'b1 : 1'b0);

assign empty_9_fu_326_p2 = ($signed(start_n_V_reg_516) + $signed(32'd7));

assign empty_fu_317_p1 = start_n_V_reg_516;

assign grp_fu_364_p0 = lhs_V_2_reg_551;

assign grp_fu_364_p1 = grp_fu_364_p10;

assign grp_fu_364_p10 = total_v_V;

assign i_V_fu_305_p4 = {{task_in[131:100]}};

assign icmp_ln879_fu_243_p2 = ((task_in_ttype_V_load_fu_234_p4 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln887_1_fu_351_p2 = (($signed(t_V_reg_175) < $signed(n_V_reg_534)) ? 1'b1 : 1'b0);

assign icmp_ln887_2_fu_372_p2 = (($signed(ngh_cnt_V_reg_545) < $signed(n_V_reg_534)) ? 1'b1 : 1'b0);

assign icmp_ln887_fu_346_p2 = (($signed(sext_ln887_fu_342_p1) < $signed(zext_ln177_1_reg_540)) ? 1'b1 : 1'b0);

assign initialized_V_load_load_fu_185_p1 = initialized_V;

assign lhs_V_2_fu_338_p1 = i_V_fu_305_p4;

assign lhs_V_fu_262_p1 = $signed(base_degree_V);

assign ngh_cnt_V_1_fu_462_p2 = ($signed(t_V_reg_175) + $signed(32'd1));

assign ngh_cnt_V_fu_331_p3 = ((empty_8_fu_320_p2[0:0] === 1'b1) ? empty_9_fu_326_p2 : start_n_V_reg_516);

assign p_Result_s_fu_429_p5 = {{p_Val2_s_fu_98[63:32]}, {l1_V_RDATA}};

assign ret_V_1_fu_299_p2 = (zext_ln177_fu_295_p1 + 33'd7);

assign ret_V_fu_270_p2 = ($signed(lhs_V_fu_262_p1) + $signed(rhs_V_fu_266_p1));

assign rhs_V_fu_266_p1 = vid_V_fu_249_p4;

assign sext_ln177_1_fu_389_p1 = $signed(tmp_1_fu_379_p5);

assign sext_ln177_fu_452_p1 = $signed(tmp_fu_441_p5);

assign sext_ln544_1_fu_398_p1 = $signed(base_neighbor_V);

assign sext_ln544_2_fu_402_p1 = t_V_reg_175;

assign sext_ln544_3_fu_412_p1 = $signed(add_ln544_reg_587);

assign sext_ln544_fu_276_p1 = $signed(ret_V_fu_270_p2);

assign sext_ln887_fu_342_p1 = t_V_reg_175;

assign start_n_V_fu_286_p4 = {{task_in[99:68]}};

assign task_in_ttype_V_load_fu_234_p4 = {{task_in[67:64]}};

assign task_out_V_TVALID = regslice_both_task_out_V_U_vld_out;

assign tmp_1_fu_379_p5 = {{{{i_V_reg_529}, {ngh_cnt_V_reg_545}}, {4'd4}}, {trunc_ln176_fu_376_p1}};

assign tmp_fu_441_p5 = {{{{p_Result_s_fu_429_p5}, {4'd1}}, {l1_V_RDATA}}, {child_ts_V_reg_568}};

assign trunc_ln176_fu_376_p1 = task_in[63:0];

assign vid_V_fu_249_p4 = {{task_in[63:32]}};

assign zext_ln177_1_fu_314_p1 = ret_V_1_reg_524;

assign zext_ln177_fu_295_p1 = $unsigned(start_n_V_fu_286_p4);

always @ (posedge ap_clk) begin
    zext_ln177_1_reg_540[33] <= 1'b0;
    lhs_V_2_reg_551[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //mis_hls
